def POM_PATH = "Pineapple/Pineapple/pom.xml"

pipeline {
    agent any

    tools {
        // Install the Maven version configured as "M3" and add it to the path.
        maven "M3"
    }

    stages {
        
        // a. Compilación del código fuente. Haga que el “build” falle cuando existan errores de compilación. 
        stage('Compilación') {
            steps {
                // Get some code from a GitHub repository
                git url:'https://github.com/NicoCasas/Gestion_de_la_Calidad.git', branch: 'main'

                // Run Maven on a Unix agent.
                sh "mvn clean package -DskipTest=True -Djacoco.skip=true -f " + POM_PATH
            }
        }

        // b. Correr CheckStyle sobre el código fuente. Haga que el “build” falle cuando la cantidad de errores supere la cantidad que había en el “build” anterior. 
        /*stage('CheckStyle') {
            steps {
                sh "mvn checkstyle:check -f " + POM_PATH
            }
        }

        // c. Correr PMD sobre el código fuente. Haga que el “build” falle cuando la cantidad de errores supere la cantidad que había en el “build” anterior. 
        stage('PMD') {
            steps {
                sh "mvn pmd:aggregate-pmd-check -f " + POM_PATH
            }
        }

        // d. Correr PMD CPD sobre el código fuente. Haga que el “build” falle cuando la cantidad de errores supere la cantidad que había en el “build” anterior. 
        stage('PMD CPD') {
            steps {
                sh "mvn pmd:aggregate-cpd-check -f " + POM_PATH
            }
        }

        // e. Correr FindBugs sobre el código fuente. Haga que el “build” falle cuando la cantidad de errores supere la cantidad que había en el “build” anterior.
        stage('FindBugs') {
            steps {
                sh "mvn com.github.spotbugs:spotbugs-maven-plugin:4.4.2.2:spotbugs -f " + POM_PATH
            }
        }
    
        // f. Correr las pruebas unitarias. Calculando la cobertura de código. Haga que el build falle cuando alguna prueba no pase o el nivel de cobertura de código baje.
        stage('Pruebas Unitarias') {
            steps {
                sh "mvn clean verify -f "  + POM_PATH
            }
        }*/
    }
    post {
        always {
            recordIssues tools: ( [checkStyle(), pmdParser(), cpd(), spotBugs()])

            chuckNorris()
        }
    }
}
