def pom_path = "Pineapple/Pineapple/pom.xml"

pipeline {
    agent any

    tools {
        // Install the Maven version configured as "M3" and add it to the path.
        maven "MAVEN_HOME"
    }

    stages {
        stage('Build') {
            steps {
                // Get some code from a GitHub repository
                git url:'https://github.com/NicoCasas/Gestion_de_la_Calidad.git', branch: 'main'

                // Run Maven on a Unix agent.
                sh "mvn clean package -DskipTest=True -f " + pom_path
            }
        }

       stage('Test') {
            steps {
                sh "mvn test -f "  + pom_path
            }
        }
    }
}
